language: python
dist: xenial
sudo: true

python:
  - 3.6
  - 3.7

install:
  - pip install -q -r requirements-dev.txt codecov

script:
  - flake8
  - pytest ConsultaCNPJ/ --cov=ConsultaCNPJ

after_success:
  - codecov